//country with country code
module.exports.country = [
    { code: 'US', name: 'United States' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'CA', name: 'Canada' },
    { code: 'AF', name: 'Afghanistan' },
    { code: 'AX', name: 'Aland Islands' },
    { code: 'AL', name: 'Albania' },
    { code: 'DZ', name: 'Algeria' },
    { code: 'AS', name: 'American Samoa' },
    { code: 'AD', name: 'Andorra' },
    { code: 'AO', name: 'Angola' },
    { code: 'AI', name: 'Anguilla' },
    { code: 'AQ', name: 'Antarctica' },
    { code: 'AG', name: 'Antigua And Barbuda' },
    { code: 'AR', name: 'Argentina' },
    { code: 'AM', name: 'Armenia' },
    { code: 'AN', name: 'Netherlands Antilles' },
    { code: 'AW', name: 'Aruba' },
    { code: 'AU', name: 'Australia' },
    { code: 'AT', name: 'Austria' },
    { code: 'AZ', name: 'Azerbaijan' },
    { code: 'BS', name: 'Bahamas' },
    { code: 'BH', name: 'Bahrain' },
    { code: 'BD', name: 'Bangladesh' },
    { code: 'BB', name: 'Barbados' },
    { code: 'BY', name: 'Belarus' },
    { code: 'BE', name: 'Belgium' },
    { code: 'BZ', name: 'Belize' },
    { code: 'BJ', name: 'Benin' },
    { code: 'BM', name: 'Bermuda' },
    { code: 'BT', name: 'Bhutan' },
    { code: 'BO', name: 'Bolivia' },
    { code: 'BA', name: 'Bosnia And Herzegovina' },
    { code: 'BW', name: 'Botswana' },
    { code: 'BV', name: 'Bouvet Island' },
    { code: 'BR', name: 'Brazil' },
    { code: 'IO', name: 'British Indian Ocean Territory' },
    { code: 'BN', name: 'Brunei Darussalam' },
    { code: 'BG', name: 'Bulgaria' },
    { code: 'BF', name: 'Burkina Faso' },
    { code: 'BI', name: 'Burundi' },
    { code: 'KH', name: 'Cambodia' },
    { code: 'CM', name: 'Cameroon' },
    { code: 'CA', name: 'Canada' },
    { code: 'CV', name: 'Cape Verde' },
    { code: 'KY', name: 'Cayman Islands' },
    { code: 'CF', name: 'Central African Republic' },
    { code: 'TD', name: 'Chad' },
    { code: 'CL', name: 'Chile' },
    { code: 'CN', name: 'China' },
    { code: 'CX', name: 'Christmas Island' },
    { code: 'CC', name: 'Cocos (Keeling) Islands' },
    { code: 'CO', name: 'Colombia' },
    { code: 'KM', name: 'Comoros' },
    { code: 'CG', name: 'Congo' },
    { code: 'CD', name: 'Congo, Democratic Republic' },
    { code: 'CK', name: 'Cook Islands' },
    { code: 'CR', name: 'Costa Rica' },
    { code: 'CI', name: 'Cote D\'Ivoire' },
    { code: 'HR', name: 'Croatia' },
    { code: 'CU', name: 'Cuba' },
    { code: 'CY', name: 'Cyprus' },
    { code: 'CZ', name: 'Czech Republic' },
    { code: 'DK', name: 'Denmark' },
    { code: 'DJ', name: 'Djibouti' },
    { code: 'DM', name: 'Dominica' },
    { code: 'DO', name: 'Dominican Republic' },
    { code: 'EC', name: 'Ecuador' },
    { code: 'EG', name: 'Egypt' },
    { code: 'SV', name: 'El Salvador' },
    { code: 'GQ', name: 'Equatorial Guinea' },
    { code: 'ER', name: 'Eritrea' },
    { code: 'EE', name: 'Estonia' },
    { code: 'ET', name: 'Ethiopia' },
    { code: 'FK', name: 'Falkland Islands (Malvinas)' },
    { code: 'FO', name: 'Faroe Islands' },
    { code: 'FJ', name: 'Fiji' },
    { code: 'FI', name: 'Finland' },
    { code: 'FR', name: 'France' },
    { code: 'GF', name: 'French Guiana' },
    { code: 'PF', name: 'French Polynesia' },
    { code: 'TF', name: 'French Southern Territories' },
    { code: 'GA', name: 'Gabon' },
    { code: 'GM', name: 'Gambia' },
    { code: 'GE', name: 'Georgia' },
    { code: 'DE', name: 'Germany' },
    { code: 'GH', name: 'Ghana' },
    { code: 'GI', name: 'Gibraltar' },
    { code: 'GR', name: 'Greece' },
    { code: 'GL', name: 'Greenland' },
    { code: 'GD', name: 'Grenada' },
    { code: 'GP', name: 'Guadeloupe' },
    { code: 'GU', name: 'Guam' },
    { code: 'GT', name: 'Guatemala' },
    { code: 'GG', name: 'Guernsey' },
    { code: 'GN', name: 'Guinea' },
    { code: 'GW', name: 'Guinea-Bissau' },
    { code: 'GY', name: 'Guyana' },
    { code: 'HT', name: 'Haiti' },
    { code: 'HM', name: 'Heard Island & Mcdonald Islands' },
    { code: 'VA', name: 'Holy See (Vatican City State)' },
    { code: 'HN', name: 'Honduras' },
    { code: 'HK', name: 'Hong Kong' },
    { code: 'HU', name: 'Hungary' },
    { code: 'IS', name: 'Iceland' },
    { code: 'IN', name: 'India' },
    { code: 'ID', name: 'Indonesia' },
    { code: 'IR', name: 'Iran, Islamic Republic Of' },
    { code: 'IQ', name: 'Iraq' },
    { code: 'IE', name: 'Ireland' },
    { code: 'IM', name: 'Isle Of Man' },
    { code: 'IL', name: 'Israel' },
    { code: 'IT', name: 'Italy' },
    { code: 'JM', name: 'Jamaica' },
    { code: 'JP', name: 'Japan' },
    { code: 'JE', name: 'Jersey' },
    { code: 'JO', name: 'Jordan' },
    { code: 'KZ', name: 'Kazakhstan' },
    { code: 'KE', name: 'Kenya' },
    { code: 'KI', name: 'Kiribati' },
    { code: 'KR', name: 'Korea' },
    { code: 'KW', name: 'Kuwait' },
    { code: 'KG', name: 'Kyrgyzstan' },
    { code: 'LA', name: 'Lao People\'s Democratic Republic' },
    { code: 'LV', name: 'Latvia' },
    { code: 'LB', name: 'Lebanon' },
    { code: 'LS', name: 'Lesotho' },
    { code: 'LR', name: 'Liberia' },
    { code: 'LY', name: 'Libyan Arab Jamahiriya' },
    { code: 'LI', name: 'Liechtenstein' },
    { code: 'LT', name: 'Lithuania' },
    { code: 'LU', name: 'Luxembourg' },
    { code: 'MO', name: 'Macao' },
    { code: 'MK', name: 'Macedonia' },
    { code: 'MG', name: 'Madagascar' },
    { code: 'MW', name: 'Malawi' },
    { code: 'MY', name: 'Malaysia' },
    { code: 'MV', name: 'Maldives' },
    { code: 'ML', name: 'Mali' },
    { code: 'MT', name: 'Malta' },
    { code: 'MH', name: 'Marshall Islands' },
    { code: 'MQ', name: 'Martinique' },
    { code: 'MR', name: 'Mauritania' },
    { code: 'MU', name: 'Mauritius' },
    { code: 'YT', name: 'Mayotte' },
    { code: 'MX', name: 'Mexico' },
    { code: 'FM', name: 'Micronesia, Federated States Of' },
    { code: 'MD', name: 'Moldova' },
    { code: 'MC', name: 'Monaco' },
    { code: 'MN', name: 'Mongolia' },
    { code: 'ME', name: 'Montenegro' },
    { code: 'MS', name: 'Montserrat' },
    { code: 'MA', name: 'Morocco' },
    { code: 'MZ', name: 'Mozambique' },
    { code: 'MM', name: 'Myanmar' },
    { code: 'NA', name: 'Namibia' },
    { code: 'NR', name: 'Nauru' },
    { code: 'NP', name: 'Nepal' },
    { code: 'NL', name: 'Netherlands' },
    { code: 'AN', name: 'Netherlands Antilles' },
    { code: 'NC', name: 'New Caledonia' },
    { code: 'NZ', name: 'New Zealand' },
    { code: 'NI', name: 'Nicaragua' },
    { code: 'NE', name: 'Niger' },
    { code: 'NG', name: 'Nigeria' },
    { code: 'NU', name: 'Niue' },
    { code: 'NF', name: 'Norfolk Island' },
    { code: 'MP', name: 'Northern Mariana Islands' },
    { code: 'NO', name: 'Norway' },
    { code: 'OM', name: 'Oman' },
    { code: 'PK', name: 'Pakistan' },
    { code: 'PW', name: 'Palau' },
    { code: 'PS', name: 'Palestinian Territory, Occupied' },
    { code: 'PA', name: 'Panama' },
    { code: 'PG', name: 'Papua New Guinea' },
    { code: 'PY', name: 'Paraguay' },
    { code: 'PE', name: 'Peru' },
    { code: 'PH', name: 'Philippines' },
    { code: 'PN', name: 'Pitcairn' },
    { code: 'PL', name: 'Poland' },
    { code: 'PT', name: 'Portugal' },
    { code: 'PR', name: 'Puerto Rico' },
    { code: 'QA', name: 'Qatar' },
    { code: 'RE', name: 'Reunion' },
    { code: 'RO', name: 'Romania' },
    { code: 'RU', name: 'Russian Federation' },
    { code: 'RW', name: 'Rwanda' },
    { code: 'BL', name: 'Saint Barthelemy' },
    { code: 'SH', name: 'Saint Helena' },
    { code: 'KN', name: 'Saint Kitts And Nevis' },
    { code: 'LC', name: 'Saint Lucia' },
    { code: 'MF', name: 'Saint Martin' },
    { code: 'PM', name: 'Saint Pierre And Miquelon' },
    { code: 'VC', name: 'Saint Vincent And Grenadines' },
    { code: 'WS', name: 'Samoa' },
    { code: 'SM', name: 'San Marino' },
    { code: 'ST', name: 'Sao Tome And Principe' },
    { code: 'SA', name: 'Saudi Arabia' },
    { code: 'SN', name: 'Senegal' },
    { code: 'RS', name: 'Serbia' },
    { code: 'SC', name: 'Seychelles' },
    { code: 'SL', name: 'Sierra Leone' },
    { code: 'SG', name: 'Singapore' },
    { code: 'SK', name: 'Slovakia' },
    { code: 'SI', name: 'Slovenia' },
    { code: 'SB', name: 'Solomon Islands' },
    { code: 'SO', name: 'Somalia' },
    { code: 'ZA', name: 'South Africa' },
    { code: 'GS', name: 'South Georgia And Sandwich Isl.' },
    { code: 'ES', name: 'Spain' },
    { code: 'LK', name: 'Sri Lanka' },
    { code: 'SD', name: 'Sudan' },
    { code: 'SR', name: 'Suriname' },
    { code: 'SJ', name: 'Svalbard And Jan Mayen' },
    { code: 'SZ', name: 'Swaziland' },
    { code: 'SE', name: 'Sweden' },
    { code: 'CH', name: 'Switzerland' },
    { code: 'SY', name: 'Syrian Arab Republic' },
    { code: 'TW', name: 'Taiwan' },
    { code: 'TJ', name: 'Tajikistan' },
    { code: 'TZ', name: 'Tanzania' },
    { code: 'TH', name: 'Thailand' },
    { code: 'TL', name: 'Timor-Leste' },
    { code: 'TG', name: 'Togo' },
    { code: 'TK', name: 'Tokelau' },
    { code: 'TO', name: 'Tonga' },
    { code: 'TT', name: 'Trinidad And Tobago' },
    { code: 'TN', name: 'Tunisia' },
    { code: 'TR', name: 'Turkey' },
    { code: 'TM', name: 'Turkmenistan' },
    { code: 'TC', name: 'Turks And Caicos Islands' },
    { code: 'TV', name: 'Tuvalu' },
    { code: 'UG', name: 'Uganda' },
    { code: 'UA', name: 'Ukraine' },
    { code: 'AE', name: 'United Arab Emirates' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'US', name: 'United States' },
    { code: 'UM', name: 'United States Outlying Islands' },
    { code: 'UY', name: 'Uruguay' },
    { code: 'UZ', name: 'Uzbekistan' },
    { code: 'VU', name: 'Vanuatu' },
    { code: 'VE', name: 'Venezuela' },
    { code: 'VN', name: 'Viet Nam' },
    { code: 'VG', name: 'Virgin Islands, British' },
    { code: 'VI', name: 'Virgin Islands, U.S.' },
    { code: 'WF', name: 'Wallis And Futuna' },
    { code: 'EH', name: 'Western Sahara' },
    { code: 'YE', name: 'Yemen' },
    { code: 'ZM', name: 'Zambia' },
    { code: 'ZW', name: 'Zimbabwe' },
];
//language with language code
module.exports.language = [
    { code: 'ab', name: 'Abkhazian' },
    { code: 'aa', name: 'Afar ' },
    { code: 'af', name: 'Afrikaans ' },
    { code: 'ak', name: 'Akan ' },
    { code: 'sq', name: 'Albanian ' },
    { code: 'am', name: 'Amharic ' },
    { code: 'ar', name: 'Arabic ' },
    { code: 'an', name: 'Aragonese ' },
    { code: 'hy', name: 'Armenian ' },
    { code: 'as', name: 'Assamese ' },
    { code: 'av', name: 'Avaric ' },
    { code: 'ae', name: 'Avestan ' },
    { code: 'ay', name: 'Aymara ' },
    { code: 'az', name: 'Azerbaijani ' },
    { code: 'bm', name: 'Bambara ' },
    { code: 'ba', name: 'Bashkir ' },
    { code: 'eu', name: 'Basque ' },
    { code: 'be', name: 'Belarusian ' },
    { code: 'bn', name: 'Bengali ' },
    { code: 'bh', name: 'Bihari languages ' },
    { code: 'bi', name: 'Bislama ' },
    { code: 'bs', name: 'Bosnian ' },
    { code: 'br', name: 'Breton ' },
    { code: 'bg', name: 'Bulgarian ' },
    { code: 'my', name: 'Burmese ' },
    { code: 'ca', name: 'Catalan, Valencian ' },
    { code: 'km', name: 'Central Khmer ' },
    { code: 'ch', name: 'Chamorro ' },
    { code: 'ce', name: 'Chechen ' },
    { code: 'ny', name: 'Chichewa, Chewa, Nyanja ' },
    { code: 'zh', name: 'Chinese ' },
    { code: 'cu', name: 'Church Slavonic, Old Bulgarian, Old Church Slavonic ' },
    { code: 'cv', name: 'Chuvash ' },
    { code: 'kw', name: 'Cornish ' },
    { code: 'co', name: 'Corsican ' },
    { code: 'cr', name: 'Cree ' },
    { code: 'hr', name: 'Croatian ' },
    { code: 'cs', name: 'Czech ' },
    { code: 'da', name: 'Danish ' },
    { code: 'dv', name: 'Divehi, Dhivehi, Maldivian ' },
    { code: 'nl', name: 'Dutch, Flemish ' },
    { code: 'dz', name: 'Dzongkha ' },
    { code: 'en', name: 'English ' },
    { code: 'eo', name: 'Esperanto ' },
    { code: 'et', name: 'Estonian ' },
    { code: 'ee', name: 'Ewe ' },
    { code: 'fo', name: 'Faroese ' },
    { code: 'fj', name: 'Fijian ' },
    { code: 'fi', name: 'Finnish ' },
    { code: 'fr', name: 'French ' },
    { code: 'ff', name: 'Fulah ' },
    { code: 'gd', name: 'Gaelic, Scottish Gaelic ' },
    { code: 'gl', name: 'Galician ' },
    { code: 'lg', name: 'Ganda ' },
    { code: 'ka', name: 'Georgian ' },
    { code: 'de', name: 'German ' },
    { code: 'ki', name: 'Gikuyu, Kikuyu ' },
    { code: 'el', name: 'Greek (Modern) ' },
    { code: 'kl', name: 'Greenlandic, Kalaallisut ' },
    { code: 'gn', name: 'Guarani ' },
    { code: 'gu', name: 'Gujarati ' },
    { code: 'ht', name: 'Haitian, Haitian Creole ' },
    { code: 'ha', name: 'Hausa ' },
    { code: 'he', name: 'Hebrew ' },
    { code: 'hz', name: 'Herero ' },
    { code: 'hi', name: 'Hindi ' },
    { code: 'ho', name: 'Hiri Motu ' },
    { code: 'hu', name: 'Hungarian ' },
    { code: 'is', name: 'Icelandic ' },
    { code: 'io', name: 'Ido ' },
    { code: 'ig', name: 'Igbo ' },
    { code: 'id', name: 'Indonesian ' },
    { code: 'ia', name: 'Interlingua (International Auxiliary Language Association) ' },
    { code: 'ie', name: 'Interlingue ' },
    { code: 'iu', name: 'Inuktitut ' },
    { code: 'ik', name: 'Inupiaq ' },
    { code: 'ga', name: 'Irish ' },
    { code: 'it', name: 'Italian ' },
    { code: 'ja', name: 'Japanese ' },
    { code: 'jv', name: 'Javanese ' },
    { code: 'kn', name: 'Kannada ' },
    { code: 'kr', name: 'Kanuri ' },
    { code: 'ks', name: 'Kashmiri ' },
    { code: 'kk', name: 'Kazakh ' },
    { code: 'rw', name: 'Kinyarwanda ' },
    { code: 'kv', name: 'Komi ' },
    { code: 'kg', name: 'Kongo ' },
    { code: 'ko', name: 'Korean ' },
    { code: 'kj', name: 'Kwanyama, Kuanyama ' },
    { code: 'ku', name: 'Kurdish ' },
    { code: 'ky', name: 'Kyrgyz ' },
    { code: 'lo', name: 'Lao ' },
    { code: 'la', name: 'Latin ' },
    { code: 'lv', name: 'Latvian ' },
    { code: 'lb', name: 'Letzeburgesch, Luxembourgish ' },
    { code: 'li', name: 'Limburgish, Limburgan, Limburger ' },
    { code: 'ln', name: 'Lingala ' },
    { code: 'lt', name: 'Lithuanian ' },
    { code: 'lu', name: 'Luba-Katanga ' },
    { code: 'mk', name: 'Macedonian ' },
    { code: 'mg', name: 'Malagasy ' },
    { code: 'ms', name: 'Malay ' },
    { code: 'ml', name: 'Malayalam ' },
    { code: 'mt', name: 'Maltese ' },
    { code: 'gv', name: 'Manx ' },
    { code: 'mi', name: 'Maori ' },
    { code: 'mr', name: 'Marathi ' },
    { code: 'mh', name: 'Marshallese ' },
    { code: 'ro', name: 'Moldovan, Moldavian, Romanian ' },
    { code: 'mn', name: 'Mongolian ' },
    { code: 'na', name: 'Nauru ' },
    { code: 'nv', name: 'Navajo, Navaho ' },
    { code: 'nd', name: 'Northern Ndebele ' },
    { code: 'ng', name: 'Ndonga ' },
    { code: 'ne', name: 'Nepali ' },
    { code: 'se', name: 'Northern Sami ' },
    { code: 'no', name: 'Norwegian ' },
    { code: 'nb', name: 'Norwegian Bokmål ' },
    { code: 'nn', name: 'Norwegian Nynorsk ' },
    { code: 'ii', name: 'Nuosu, Sichuan Yi ' },
    { code: 'oc', name: 'Occitan (post 1500) ' },
    { code: 'oj', name: 'Ojibwa ' },
    { code: 'or', name: 'Oriya ' },
    { code: 'om', name: 'Oromo ' },
    { code: 'os', name: 'Ossetian, Ossetic ' },
    { code: 'pi', name: 'Pali ' },
    { code: 'pa', name: 'Panjabi, Punjabi ' },
    { code: 'ps', name: 'Pashto, Pushto ' },
    { code: 'fa', name: 'Persian ' },
    { code: 'pl', name: 'Polish ' },
    { code: 'pt', name: 'Portuguese ' },
    { code: 'qu', name: 'Quechua ' },
    { code: 'rm', name: 'Romansh ' },
    { code: 'rn', name: 'Rundi ' },
    { code: 'ru', name: 'Russian ' },
    { code: 'sm', name: 'Samoan ' },
    { code: 'sg', name: 'Sango ' },
    { code: 'sa', name: 'Sanskrit ' },
    { code: 'sc', name: 'Sardinian ' },
    { code: 'sr', name: 'Serbian ' },
    { code: 'sn', name: 'Shona ' },
    { code: 'sd', name: 'Sindhi ' },
    { code: 'si', name: 'Sinhala, Sinhalese ' },
    { code: 'sk', name: 'Slovak ' },
    { code: 'sl', name: 'Slovenian ' },
    { code: 'so', name: 'Somali ' },
    { code: 'st', name: 'Sotho, Southern ' },
    { code: 'nr', name: 'South Ndebele ' },
    { code: 'es', name: 'Spanish, Castilian ' },
    { code: 'su', name: 'Sundanese ' },
    { code: 'sw', name: 'Swahili ' },
    { code: 'ss', name: 'Swati ' },
    { code: 'sv', name: 'Swedish ' },
    { code: 'tl', name: 'Tagalog ' },
    { code: 'ty', name: 'Tahitian ' },
    { code: 'tg', name: 'Tajik ' },
    { code: 'ta', name: 'Tamil ' },
    { code: 'tt', name: 'Tatar ' },
    { code: 'te', name: 'Telugu ' },
    { code: 'th', name: 'Thai ' },
    { code: 'bo', name: 'Tibetan ' },
    { code: 'ti', name: 'Tigrinya ' },
    { code: 'to', name: 'Tonga (Tonga Islands) ' },
    { code: 'ts', name: 'Tsonga ' },
    { code: 'tn', name: 'Tswana ' },
    { code: 'tr', name: 'Turkish ' },
    { code: 'tk', name: 'Turkmen ' },
    { code: 'tw', name: 'Twi ' },
    { code: 'ug', name: 'Uighur, Uyghur ' },
    { code: 'uk', name: 'Ukrainian ' },
    { code: 'ur', name: 'Urdu ' },
    { code: 'uz', name: 'Uzbek ' },
    { code: 've', name: 'Venda ' },
    { code: 'vi', name: 'Vietnamese ' },
    { code: 'vo', name: 'Volap_k ' },
    { code: 'wa', name: 'Walloon ' },
    { code: 'cy', name: 'Welsh ' },
    { code: 'fy', name: 'Western Frisian ' },
    { code: 'wo', name: 'Wolof ' },
    { code: 'xh', name: 'Xhosa ' },
    { code: 'yi', name: 'Yiddish ' },
    { code: 'yo', name: 'Yoruba ' },
    { code: 'za', name: 'Zhuang, Chuang ' },
    { code: 'zu', name: 'Zulu ' }
];
//country name with phone codes
module.exports.countryCodes = [
    { 'name': 'ANDORRA', 'code': '376' },
    { 'name': 'UNITED ARAB EMIRATES', 'code': '971' },
    { 'name': 'AFGHANISTAN', 'code': '93' },
    { 'name': 'ANTIGUA AND BARBUDA', 'code': '1268' },
    { 'name': 'ANGUILLA', 'code': '1264' },
    { 'name': 'ALBANIA', 'code': '355' },
    { 'name': 'ARMENIA', 'code': '374' },
    { 'name': 'NETHERLANDS ANTILLES', 'code': '599' },
    { 'name': 'ANGOLA', 'code': '244' },
    { 'name': 'ANTARCTICA', 'code': '672' },
    { 'name': 'ARGENTINA', 'code': '54' },
    { 'name': 'AMERICAN SAMOA', 'code': '1684' },
    { 'name': 'AUSTRIA', 'code': '43' },
    { 'name': 'AUSTRALIA', 'code': '61' },
    { 'name': 'ARUBA', 'code': '297' },
    { 'name': 'AZERBAIJAN', 'code': '994' },
    { 'name': 'BOSNIA AND HERZEGOVINA', 'code': '387' },
    { 'name': 'BARBADOS', 'code': '1246' },
    { 'name': 'BANGLADESH', 'code': '880' },
    { 'name': 'BELGIUM', 'code': '32' },
    { 'name': 'BURKINA FASO', 'code': '226' },
    { 'name': 'BULGARIA', 'code': '359' },
    { 'name': 'BAHRAIN', 'code': '973' },
    { 'name': 'BURUNDI', 'code': '257' },
    { 'name': 'BENIN', 'code': '229' },
    { 'name': 'SAINT BARTHELEMY', 'code': '590' },
    { 'name': 'BERMUDA', 'code': '1441' },
    { 'name': 'BRUNEI DARUSSALAM', 'code': '673' },
    { 'name': 'BOLIVIA', 'code': '591' },
    { 'name': 'BRAZIL', 'code': '55' },
    { 'name': 'BAHAMAS', 'code': '1242' },
    { 'name': 'BHUTAN', 'code': '975' },
    { 'name': 'BOTSWANA', 'code': '267' },
    { 'name': 'BELARUS', 'code': '375' },
    { 'name': 'BELIZE', 'code': '501' },
    { 'name': 'CANADA', 'code': '1' },
    { 'name': 'COCOS (KEELING) ISLANDS', 'code': '61' },
    { 'name': 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'code': '243' },
    { 'name': 'CENTRAL AFRICAN REPUBLIC', 'code': '236' },
    { 'name': 'CONGO', 'code': '242' },
    { 'name': 'SWITZERLAND', 'code': '41' },
    { 'name': 'COTE D IVOIRE', 'code': '225' },
    { 'name': 'COOK ISLANDS', 'code': '682' },
    { 'name': 'CHILE', 'code': '56' },
    { 'name': 'CAMEROON', 'code': '237' },
    { 'name': 'CHINA', 'code': '86' },
    { 'name': 'COLOMBIA', 'code': '57' },
    { 'name': 'COSTA RICA', 'code': '506' },
    { 'name': 'CUBA', 'code': '53' },
    { 'name': 'CAPE VERDE', 'code': '238' },
    { 'name': 'CHRISTMAS ISLAND', 'code': '61' },
    { 'name': 'CYPRUS', 'code': '357' },
    { 'name': 'CZECH REPUBLIC', 'code': '420' },
    { 'name': 'GERMANY', 'code': '49' },
    { 'name': 'DJIBOUTI', 'code': '253' },
    { 'name': 'DENMARK', 'code': '45' },
    { 'name': 'DOMINICA', 'code': '1767' },
    { 'name': 'DOMINICAN REPUBLIC', 'code': '1809' },
    { 'name': 'ALGERIA', 'code': '213' },
    { 'name': 'ECUADOR', 'code': '593' },
    { 'name': 'ESTONIA', 'code': '372' },
    { 'name': 'EGYPT', 'code': '20' },
    { 'name': 'ERITREA', 'code': '291' },
    { 'name': 'SPAIN', 'code': '34' },
    { 'name': 'ETHIOPIA', 'code': '251' },
    { 'name': 'FINLAND', 'code': '358' },
    { 'name': 'FIJI', 'code': '679' },
    { 'name': 'FALKLAND ISLANDS (MALVINAS)', 'code': '500' },
    { 'name': 'MICRONESIA, FEDERATED STATES OF', 'code': '691' },
    { 'name': 'FAROE ISLANDS', 'code': '298' },
    { 'name': 'FRANCE', 'code': '33' },
    { 'name': 'GABON', 'code': '241' },
    { 'name': 'UNITED KINGDOM', 'code': '44' },
    { 'name': 'GRENADA', 'code': '1473' },
    { 'name': 'GEORGIA', 'code': '995' },
    { 'name': 'GHANA', 'code': '233' },
    { 'name': 'GIBRALTAR', 'code': '350' },
    { 'name': 'GREENLAND', 'code': '299' },
    { 'name': 'GAMBIA', 'code': '220' },
    { 'name': 'GUINEA', 'code': '224' },
    { 'name': 'EQUATORIAL GUINEA', 'code': '240' },
    { 'name': 'GREECE', 'code': '30' },
    { 'name': 'GUATEMALA', 'code': '502' },
    { 'name': 'GUAM', 'code': '1671' },
    { 'name': 'GUINEA-BISSAU', 'code': '245' },
    { 'name': 'GUYANA', 'code': '592' },
    { 'name': 'HONG KONG', 'code': '852' },
    { 'name': 'HONDURAS', 'code': '504' },
    { 'name': 'CROATIA', 'code': '385' },
    { 'name': 'HAITI', 'code': '509' },
    { 'name': 'HUNGARY', 'code': '36' },
    { 'name': 'INDONESIA', 'code': '62' },
    { 'name': 'IRELAND', 'code': '353' },
    { 'name': 'ISRAEL', 'code': '972' },
    { 'name': 'ISLE OF MAN', 'code': '44' },
    { 'name': 'INDIA', 'code': '91' },
    { 'name': 'IRAQ', 'code': '964' },
    { 'name': 'IRAN, ISLAMIC REPUBLIC OF', 'code': '98' },
    { 'name': 'ICELAND', 'code': '354' },
    { 'name': 'ITALY', 'code': '39' },
    { 'name': 'JAMAICA', 'code': '1876' },
    { 'name': 'JORDAN', 'code': '962' },
    { 'name': 'JAPAN', 'code': '81' },
    { 'name': 'KENYA', 'code': '254' },
    { 'name': 'KYRGYZSTAN', 'code': '996' },
    { 'name': 'CAMBODIA', 'code': '855' },
    { 'name': 'KIRIBATI', 'code': '686' },
    { 'name': 'COMOROS', 'code': '269' },
    { 'name': 'SAINT KITTS AND NEVIS', 'code': '1869' },
    { 'name': 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF', 'code': '850' },
    { 'name': 'KOREA REPUBLIC OF', 'code': '82' },
    { 'name': 'KUWAIT', 'code': '965' },
    { 'name': 'CAYMAN ISLANDS', 'code': '1345' },
    { 'name': 'KAZAKSTAN', 'code': '7' },
    { 'name': 'LAO PEOPLES DEMOCRATIC REPUBLIC', 'code': '856' },
    { 'name': 'LEBANON', 'code': '961' },
    { 'name': 'SAINT LUCIA', 'code': '1758' },
    { 'name': 'LIECHTENSTEIN', 'code': '423' },
    { 'name': 'SRI LANKA', 'code': '94' },
    { 'name': 'LIBERIA', 'code': '231' },
    { 'name': 'LESOTHO', 'code': '266' },
    { 'name': 'LITHUANIA', 'code': '370' },
    { 'name': 'LUXEMBOURG', 'code': '352' },
    { 'name': 'LATVIA', 'code': '371' },
    { 'name': 'LIBYAN ARAB JAMAHIRIYA', 'code': '218' },
    { 'name': 'MOROCCO', 'code': '212' },
    { 'name': 'MONACO', 'code': '377' },
    { 'name': 'MOLDOVA, REPUBLIC OF', 'code': '373' },
    { 'name': 'MONTENEGRO', 'code': '382' },
    { 'name': 'SAINT MARTIN', 'code': '1599' },
    { 'name': 'MADAGASCAR', 'code': '261' },
    { 'name': 'MARSHALL ISLANDS', 'code': '692' },
    { 'name': 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'code': '389' },
    { 'name': 'MALI', 'code': '223' },
    { 'name': 'MYANMAR', 'code': '95' },
    { 'name': 'MONGOLIA', 'code': '976' },
    { 'name': 'MACAU', 'code': '853' },
    { 'name': 'NORTHERN MARIANA ISLANDS', 'code': '1670' },
    { 'name': 'MAURITANIA', 'code': '222' },
    { 'name': 'MONTSERRAT', 'code': '1664' },
    { 'name': 'MALTA', 'code': '356' },
    { 'name': 'MAURITIUS', 'code': '230' },
    { 'name': 'MALDIVES', 'code': '960' },
    { 'name': 'MALAWI', 'code': '265' },
    { 'name': 'MEXICO', 'code': '52' },
    { 'name': 'MALAYSIA', 'code': '60' },
    { 'name': 'MOZAMBIQUE', 'code': '258' },
    { 'name': 'NAMIBIA', 'code': '264' },
    { 'name': 'NEW CALEDONIA', 'code': '687' },
    { 'name': 'NIGER', 'code': '227' },
    { 'name': 'NIGERIA', 'code': '234' },
    { 'name': 'NICARAGUA', 'code': '505' },
    { 'name': 'NETHERLANDS', 'code': '31' },
    { 'name': 'NORWAY', 'code': '47' },
    { 'name': 'NEPAL', 'code': '977' },
    { 'name': 'NAURU', 'code': '674' },
    { 'name': 'NIUE', 'code': '683' },
    { 'name': 'NEW ZEALAND', 'code': '64' },
    { 'name': 'OMAN', 'code': '968' },
    { 'name': 'PANAMA', 'code': '507' },
    { 'name': 'PERU', 'code': '51' },
    { 'name': 'FRENCH POLYNESIA', 'code': '689' },
    { 'name': 'PAPUA NEW GUINEA', 'code': '675' },
    { 'name': 'PHILIPPINES', 'code': '63' },
    { 'name': 'PAKISTAN', 'code': '92' },
    { 'name': 'POLAND', 'code': '48' },
    { 'name': 'SAINT PIERRE AND MIQUELON', 'code': '508' },
    { 'name': 'PITCAIRN', 'code': '870' },
    { 'name': 'PUERTO RICO', 'code': '1' },
    { 'name': 'PORTUGAL', 'code': '351' },
    { 'name': 'PALAU', 'code': '680' },
    { 'name': 'PARAGUAY', 'code': '595' },
    { 'name': 'QATAR', 'code': '974' },
    { 'name': 'ROMANIA', 'code': '40' },
    { 'name': 'SERBIA', 'code': '381' },
    { 'name': 'RUSSIAN FEDERATION', 'code': '7' },
    { 'name': 'RWANDA', 'code': '250' },
    { 'name': 'SAUDI ARABIA', 'code': '966' },
    { 'name': 'SOLOMON ISLANDS', 'code': '677' },
    { 'name': 'SEYCHELLES', 'code': '248' },
    { 'name': 'SUDAN', 'code': '249' },
    { 'name': 'SWEDEN', 'code': '46' },
    { 'name': 'SINGAPORE', 'code': '65' },
    { 'name': 'SAINT HELENA', 'code': '290' },
    { 'name': 'SLOVENIA', 'code': '386' },
    { 'name': 'SLOVAKIA', 'code': '421' },
    { 'name': 'SIERRA LEONE', 'code': '232' },
    { 'name': 'SAN MARINO', 'code': '378' },
    { 'name': 'SENEGAL', 'code': '221' },
    { 'name': 'SOMALIA', 'code': '252' },
    { 'name': 'SURINAME', 'code': '597' },
    { 'name': 'SAO TOME AND PRINCIPE', 'code': '239' },
    { 'name': 'EL SALVADOR', 'code': '503' },
    { 'name': 'SYRIAN ARAB REPUBLIC', 'code': '963' },
    { 'name': 'SWAZILAND', 'code': '268' },
    { 'name': 'TURKS AND CAICOS ISLANDS', 'code': '1649' },
    { 'name': 'CHAD', 'code': '235' },
    { 'name': 'TOGO', 'code': '228' },
    { 'name': 'THAILAND', 'code': '66' },
    { 'name': 'TAJIKISTAN', 'code': '992' },
    { 'name': 'TOKELAU', 'code': '690' },
    { 'name': 'TIMOR-LESTE', 'code': '670' },
    { 'name': 'TURKMENISTAN', 'code': '993' },
    { 'name': 'TUNISIA', 'code': '216' },
    { 'name': 'TONGA', 'code': '676' },
    { 'name': 'TURKEY', 'code': '90' },
    { 'name': 'TRINIDAD AND TOBAGO', 'code': '1868' },
    { 'name': 'TUVALU', 'code': '688' },
    { 'name': 'TAIWAN, PROVINCE OF CHINA', 'code': '886' },
    { 'name': 'TANZANIA, UNITED REPUBLIC OF', 'code': '255' },
    { 'name': 'UKRAINE', 'code': '380' },
    { 'name': 'UGANDA', 'code': '256' },
    { 'name': 'UNITED STATES', 'code': '1' },
    { 'name': 'URUGUAY', 'code': '598' },
    { 'name': 'UZBEKISTAN', 'code': '998' },
    { 'name': 'HOLY SEE (VATICAN CITY STATE)', 'code': '39' },
    { 'name': 'SAINT VINCENT AND THE GRENADINES', 'code': '1784' },
    { 'name': 'VENEZUELA', 'code': '58' },
    { 'name': 'VIRGIN ISLANDS, BRITISH', 'code': '1284' },
    { 'name': 'VIRGIN ISLANDS, U.S.', 'code': '1340' },
    { 'name': 'VIET NAM', 'code': '84' },
    { 'name': 'VANUATU', 'code': '678' },
    { 'name': 'WALLIS AND FUTUNA', 'code': '681' },
    { 'name': 'SAMOA', 'code': '685' },
    { 'name': 'KOSOVO', 'code': '381' },
    { 'name': 'YEMEN', 'code': '967' },
    { 'name': 'MAYOTTE', 'code': '262' },
    { 'name': 'SOUTH AFRICA', 'code': '27' },
    { 'name': 'ZAMBIA', 'code': '260' },
    { 'name': 'ZIMBABWE', 'code': '263' }
];
// currency with symbool, name,symbool native, decimal_digits, rounding, code, name_plural
module.exports.currency = [
    {
        "symbol": "$",
        "name": "US Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "USD",
        "name_plural": "US dollars"
    },
    {
        "symbol": "CA$",
        "name": "Canadian Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "CAD",
        "name_plural": "Canadian dollars"
    },
    {
        "symbol": "€",
        "name": "Euro",
        "symbol_native": "€",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "EUR",
        "name_plural": "euros"
    },
    {
        "symbol": "AED",
        "name": "United Arab Emirates Dirham",
        "symbol_native": "د.إ.‏",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "AED",
        "name_plural": "UAE dirhams"
    },
    {
        "symbol": "Af",
        "name": "Afghan Afghani",
        "symbol_native": "؋",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "AFN",
        "name_plural": "Afghan Afghanis"
    },
    {
        "symbol": "ALL",
        "name": "Albanian Lek",
        "symbol_native": "Lek",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "ALL",
        "name_plural": "Albanian lekë"
    },
    {
        "symbol": "AMD",
        "name": "Armenian Dram",
        "symbol_native": "դր.",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "AMD",
        "name_plural": "Armenian drams"
    },
    {
        "symbol": "AR$",
        "name": "Argentine Peso",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "ARS",
        "name_plural": "Argentine pesos"
    },
    {
        "symbol": "AU$",
        "name": "Australian Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "AUD",
        "name_plural": "Australian dollars"
    },
    {
        "symbol": "man.",
        "name": "Azerbaijani Manat",
        "symbol_native": "ман.",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "AZN",
        "name_plural": "Azerbaijani manats"
    },
    {
        "symbol": "KM",
        "name": "Bosnia-Herzegovina Convertible Mark",
        "symbol_native": "KM",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "BAM",
        "name_plural": "Bosnia-Herzegovina convertible marks"
    },
    {
        "symbol": "Tk",
        "name": "Bangladeshi Taka",
        "symbol_native": "৳",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "BDT",
        "name_plural": "Bangladeshi takas"
    },
    {
        "symbol": "BGN",
        "name": "Bulgarian Lev",
        "symbol_native": "лв.",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "BGN",
        "name_plural": "Bulgarian leva"
    },
    {
        "symbol": "BD",
        "name": "Bahraini Dinar",
        "symbol_native": "د.ب.‏",
        "decimal_digits": 3,
        "rounding": 0,
        "code": "BHD",
        "name_plural": "Bahraini dinars"
    },
    {
        "symbol": "FBu",
        "name": "Burundian Franc",
        "symbol_native": "FBu",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "BIF",
        "name_plural": "Burundian francs"
    },
    {
        "symbol": "BN$",
        "name": "Brunei Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "BND",
        "name_plural": "Brunei dollars"
    },
    {
        "symbol": "Bs",
        "name": "Bolivian Boliviano",
        "symbol_native": "Bs",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "BOB",
        "name_plural": "Bolivian bolivianos"
    },
    {
        "symbol": "R$",
        "name": "Brazilian Real",
        "symbol_native": "R$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "BRL",
        "name_plural": "Brazilian reals"
    },
    {
        "symbol": "BWP",
        "name": "Botswanan Pula",
        "symbol_native": "P",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "BWP",
        "name_plural": "Botswanan pulas"
    },
    {
        "symbol": "BYR",
        "name": "Belarusian Ruble",
        "symbol_native": "BYR",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "BYR",
        "name_plural": "Belarusian rubles"
    },
    {
        "symbol": "BZ$",
        "name": "Belize Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "BZD",
        "name_plural": "Belize dollars"
    },
    {
        "symbol": "CDF",
        "name": "Congolese Franc",
        "symbol_native": "FrCD",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "CDF",
        "name_plural": "Congolese francs"
    },
    {
        "symbol": "CHF",
        "name": "Swiss Franc",
        "symbol_native": "CHF",
        "decimal_digits": 2,
        "rounding": 0.05,
        "code": "CHF",
        "name_plural": "Swiss francs"
    },
    {
        "symbol": "CL$",
        "name": "Chilean Peso",
        "symbol_native": "$",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "CLP",
        "name_plural": "Chilean pesos"
    },
    {
        "symbol": "CN¥",
        "name": "Chinese Yuan",
        "symbol_native": "CN¥",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "CNY",
        "name_plural": "Chinese yuan"
    },
    {
        "symbol": "CO$",
        "name": "Colombian Peso",
        "symbol_native": "$",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "COP",
        "name_plural": "Colombian pesos"
    },
    {
        "symbol": "₡",
        "name": "Costa Rican Colón",
        "symbol_native": "₡",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "CRC",
        "name_plural": "Costa Rican colóns"
    },
    {
        "symbol": "CV$",
        "name": "Cape Verdean Escudo",
        "symbol_native": "CV$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "CVE",
        "name_plural": "Cape Verdean escudos"
    },
    {
        "symbol": "Kč",
        "name": "Czech Republic Koruna",
        "symbol_native": "Kč",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "CZK",
        "name_plural": "Czech Republic korunas"
    },
    {
        "symbol": "Fdj",
        "name": "Djiboutian Franc",
        "symbol_native": "Fdj",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "DJF",
        "name_plural": "Djiboutian francs"
    },
    {
        "symbol": "Dkr",
        "name": "Danish Krone",
        "symbol_native": "kr",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "DKK",
        "name_plural": "Danish kroner"
    },
    {
        "symbol": "RD$",
        "name": "Dominican Peso",
        "symbol_native": "RD$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "DOP",
        "name_plural": "Dominican pesos"
    },
    {
        "symbol": "DA",
        "name": "Algerian Dinar",
        "symbol_native": "د.ج.‏",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "DZD",
        "name_plural": "Algerian dinars"
    },
    {
        "symbol": "Ekr",
        "name": "Estonian Kroon",
        "symbol_native": "kr",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "EEK",
        "name_plural": "Estonian kroons"
    },
    {
        "symbol": "EGP",
        "name": "Egyptian Pound",
        "symbol_native": "ج.م.‏",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "EGP",
        "name_plural": "Egyptian pounds"
    },
    {
        "symbol": "Nfk",
        "name": "Eritrean Nakfa",
        "symbol_native": "Nfk",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "ERN",
        "name_plural": "Eritrean nakfas"
    },
    {
        "symbol": "Br",
        "name": "Ethiopian Birr",
        "symbol_native": "Br",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "ETB",
        "name_plural": "Ethiopian birrs"
    },
    {
        "symbol": "£",
        "name": "British Pound Sterling",
        "symbol_native": "£",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "GBP",
        "name_plural": "British pounds sterling"
    },
    {
        "symbol": "GEL",
        "name": "Georgian Lari",
        "symbol_native": "GEL",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "GEL",
        "name_plural": "Georgian laris"
    },
    {
        "symbol": "GH₵",
        "name": "Ghanaian Cedi",
        "symbol_native": "GH₵",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "GHS",
        "name_plural": "Ghanaian cedis"
    },
    {
        "symbol": "FG",
        "name": "Guinean Franc",
        "symbol_native": "FG",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "GNF",
        "name_plural": "Guinean francs"
    },
    {
        "symbol": "GTQ",
        "name": "Guatemalan Quetzal",
        "symbol_native": "Q",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "GTQ",
        "name_plural": "Guatemalan quetzals"
    },
    {
        "symbol": "HK$",
        "name": "Hong Kong Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "HKD",
        "name_plural": "Hong Kong dollars"
    },
    {
        "symbol": "HNL",
        "name": "Honduran Lempira",
        "symbol_native": "L",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "HNL",
        "name_plural": "Honduran lempiras"
    },
    {
        "symbol": "kn",
        "name": "Croatian Kuna",
        "symbol_native": "kn",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "HRK",
        "name_plural": "Croatian kunas"
    },
    {
        "symbol": "Ft",
        "name": "Hungarian Forint",
        "symbol_native": "Ft",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "HUF",
        "name_plural": "Hungarian forints"
    },
    {
        "symbol": "Rp",
        "name": "Indonesian Rupiah",
        "symbol_native": "Rp",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "IDR",
        "name_plural": "Indonesian rupiahs"
    },
    {
        "symbol": "₪",
        "name": "Israeli New Sheqel",
        "symbol_native": "₪",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "ILS",
        "name_plural": "Israeli new sheqels"
    },
    {
        "symbol": "Rs",
        "name": "Indian Rupee",
        "symbol_native": "টকা",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "INR",
        "name_plural": "Indian rupees"
    },
    {
        "symbol": "IQD",
        "name": "Iraqi Dinar",
        "symbol_native": "د.ع.‏",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "IQD",
        "name_plural": "Iraqi dinars"
    },
    {
        "symbol": "IRR",
        "name": "Iranian Rial",
        "symbol_native": "﷼",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "IRR",
        "name_plural": "Iranian rials"
    },
    {
        "symbol": "Ikr",
        "name": "Icelandic Króna",
        "symbol_native": "kr",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "ISK",
        "name_plural": "Icelandic krónur"
    },
    {
        "symbol": "J$",
        "name": "Jamaican Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "JMD",
        "name_plural": "Jamaican dollars"
    },
    {
        "symbol": "JD",
        "name": "Jordanian Dinar",
        "symbol_native": "د.أ.‏",
        "decimal_digits": 3,
        "rounding": 0,
        "code": "JOD",
        "name_plural": "Jordanian dinars"
    },
    {
        "symbol": "¥",
        "name": "Japanese Yen",
        "symbol_native": "￥",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "JPY",
        "name_plural": "Japanese yen"
    },
    {
        "symbol": "Ksh",
        "name": "Kenyan Shilling",
        "symbol_native": "Ksh",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "KES",
        "name_plural": "Kenyan shillings"
    },
    {
        "symbol": "KHR",
        "name": "Cambodian Riel",
        "symbol_native": "៛",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "KHR",
        "name_plural": "Cambodian riels"
    },
    {
        "symbol": "CF",
        "name": "Comorian Franc",
        "symbol_native": "FC",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "KMF",
        "name_plural": "Comorian francs"
    },
    {
        "symbol": "₩",
        "name": "South Korean Won",
        "symbol_native": "₩",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "KRW",
        "name_plural": "South Korean won"
    },
    {
        "symbol": "KD",
        "name": "Kuwaiti Dinar",
        "symbol_native": "د.ك.‏",
        "decimal_digits": 3,
        "rounding": 0,
        "code": "KWD",
        "name_plural": "Kuwaiti dinars"
    },
    {
        "symbol": "KZT",
        "name": "Kazakhstani Tenge",
        "symbol_native": "тңг.",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "KZT",
        "name_plural": "Kazakhstani tenges"
    },
    {
        "symbol": "LB£",
        "name": "Lebanese Pound",
        "symbol_native": "ل.ل.‏",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "LBP",
        "name_plural": "Lebanese pounds"
    },
    {
        "symbol": "SLRs",
        "name": "Sri Lankan Rupee",
        "symbol_native": "SL Re",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "LKR",
        "name_plural": "Sri Lankan rupees"
    },
    {
        "symbol": "Lt",
        "name": "Lithuanian Litas",
        "symbol_native": "Lt",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "LTL",
        "name_plural": "Lithuanian litai"
    },
    {
        "symbol": "Ls",
        "name": "Latvian Lats",
        "symbol_native": "Ls",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "LVL",
        "name_plural": "Latvian lati"
    },
    {
        "symbol": "LD",
        "name": "Libyan Dinar",
        "symbol_native": "د.ل.‏",
        "decimal_digits": 3,
        "rounding": 0,
        "code": "LYD",
        "name_plural": "Libyan dinars"
    },
    {
        "symbol": "MAD",
        "name": "Moroccan Dirham",
        "symbol_native": "د.م.‏",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "MAD",
        "name_plural": "Moroccan dirhams"
    },
    {
        "symbol": "MDL",
        "name": "Moldovan Leu",
        "symbol_native": "MDL",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "MDL",
        "name_plural": "Moldovan lei"
    },
    {
        "symbol": "MGA",
        "name": "Malagasy Ariary",
        "symbol_native": "MGA",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "MGA",
        "name_plural": "Malagasy Ariaries"
    },
    {
        "symbol": "MKD",
        "name": "Macedonian Denar",
        "symbol_native": "MKD",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "MKD",
        "name_plural": "Macedonian denari"
    },
    {
        "symbol": "MMK",
        "name": "Myanma Kyat",
        "symbol_native": "K",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "MMK",
        "name_plural": "Myanma kyats"
    },
    {
        "symbol": "MOP$",
        "name": "Macanese Pataca",
        "symbol_native": "MOP$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "MOP",
        "name_plural": "Macanese patacas"
    },
    {
        "symbol": "MURs",
        "name": "Mauritian Rupee",
        "symbol_native": "MURs",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "MUR",
        "name_plural": "Mauritian rupees"
    },
    {
        "symbol": "MX$",
        "name": "Mexican Peso",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "MXN",
        "name_plural": "Mexican pesos"
    },
    {
        "symbol": "RM",
        "name": "Malaysian Ringgit",
        "symbol_native": "RM",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "MYR",
        "name_plural": "Malaysian ringgits"
    },
    {
        "symbol": "MTn",
        "name": "Mozambican Metical",
        "symbol_native": "MTn",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "MZN",
        "name_plural": "Mozambican meticals"
    },
    {
        "symbol": "N$",
        "name": "Namibian Dollar",
        "symbol_native": "N$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "NAD",
        "name_plural": "Namibian dollars"
    },
    {
        "symbol": "₦",
        "name": "Nigerian Naira",
        "symbol_native": "₦",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "NGN",
        "name_plural": "Nigerian nairas"
    },
    {
        "symbol": "C$",
        "name": "Nicaraguan Córdoba",
        "symbol_native": "C$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "NIO",
        "name_plural": "Nicaraguan córdobas"
    },
    {
        "symbol": "Nkr",
        "name": "Norwegian Krone",
        "symbol_native": "kr",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "NOK",
        "name_plural": "Norwegian kroner"
    },
    {
        "symbol": "NPRs",
        "name": "Nepalese Rupee",
        "symbol_native": "नेरू",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "NPR",
        "name_plural": "Nepalese rupees"
    },
    {
        "symbol": "NZ$",
        "name": "New Zealand Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "NZD",
        "name_plural": "New Zealand dollars"
    },
    {
        "symbol": "OMR",
        "name": "Omani Rial",
        "symbol_native": "ر.ع.‏",
        "decimal_digits": 3,
        "rounding": 0,
        "code": "OMR",
        "name_plural": "Omani rials"
    },
    {
        "symbol": "B/.",
        "name": "Panamanian Balboa",
        "symbol_native": "B/.",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "PAB",
        "name_plural": "Panamanian balboas"
    },
    {
        "symbol": "S/.",
        "name": "Peruvian Nuevo Sol",
        "symbol_native": "S/.",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "PEN",
        "name_plural": "Peruvian nuevos soles"
    },
    {
        "symbol": "₱",
        "name": "Philippine Peso",
        "symbol_native": "₱",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "PHP",
        "name_plural": "Philippine pesos"
    },
    {
        "symbol": "PKRs",
        "name": "Pakistani Rupee",
        "symbol_native": "₨",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "PKR",
        "name_plural": "Pakistani rupees"
    },
    {
        "symbol": "zł",
        "name": "Polish Zloty",
        "symbol_native": "zł",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "PLN",
        "name_plural": "Polish zlotys"
    },
    {
        "symbol": "₲",
        "name": "Paraguayan Guarani",
        "symbol_native": "₲",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "PYG",
        "name_plural": "Paraguayan guaranis"
    },
    {
        "symbol": "QR",
        "name": "Qatari Rial",
        "symbol_native": "ر.ق.‏",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "QAR",
        "name_plural": "Qatari rials"
    },
    {
        "symbol": "RON",
        "name": "Romanian Leu",
        "symbol_native": "RON",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "RON",
        "name_plural": "Romanian lei"
    },
    {
        "symbol": "din.",
        "name": "Serbian Dinar",
        "symbol_native": "дин.",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "RSD",
        "name_plural": "Serbian dinars"
    },
    {
        "symbol": "RUB",
        "name": "Russian Ruble",
        "symbol_native": "руб.",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "RUB",
        "name_plural": "Russian rubles"
    },
    {
        "symbol": "RWF",
        "name": "Rwandan Franc",
        "symbol_native": "FR",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "RWF",
        "name_plural": "Rwandan francs"
    },
    {
        "symbol": "SR",
        "name": "Saudi Riyal",
        "symbol_native": "ر.س.‏",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "SAR",
        "name_plural": "Saudi riyals"
    },
    {
        "symbol": "SDG",
        "name": "Sudanese Pound",
        "symbol_native": "SDG",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "SDG",
        "name_plural": "Sudanese pounds"
    },
    {
        "symbol": "Skr",
        "name": "Swedish Krona",
        "symbol_native": "kr",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "SEK",
        "name_plural": "Swedish kronor"
    },
    {
        "symbol": "S$",
        "name": "Singapore Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "SGD",
        "name_plural": "Singapore dollars"
    },
    {
        "symbol": "Ssh",
        "name": "Somali Shilling",
        "symbol_native": "Ssh",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "SOS",
        "name_plural": "Somali shillings"
    },
    {
        "symbol": "SY£",
        "name": "Syrian Pound",
        "symbol_native": "ل.س.‏",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "SYP",
        "name_plural": "Syrian pounds"
    },
    {
        "symbol": "฿",
        "name": "Thai Baht",
        "symbol_native": "฿",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "THB",
        "name_plural": "Thai baht"
    },
    {
        "symbol": "DT",
        "name": "Tunisian Dinar",
        "symbol_native": "د.ت.‏",
        "decimal_digits": 3,
        "rounding": 0,
        "code": "TND",
        "name_plural": "Tunisian dinars"
    },
    {
        "symbol": "T$",
        "name": "Tongan Paʻanga",
        "symbol_native": "T$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "TOP",
        "name_plural": "Tongan paʻanga"
    },
    {
        "symbol": "TL",
        "name": "Turkish Lira",
        "symbol_native": "TL",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "TRY",
        "name_plural": "Turkish Lira"
    },
    {
        "symbol": "TT$",
        "name": "Trinidad and Tobago Dollar",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "TTD",
        "name_plural": "Trinidad and Tobago dollars"
    },
    {
        "symbol": "NT$",
        "name": "New Taiwan Dollar",
        "symbol_native": "NT$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "TWD",
        "name_plural": "New Taiwan dollars"
    },
    {
        "symbol": "TSh",
        "name": "Tanzanian Shilling",
        "symbol_native": "TSh",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "TZS",
        "name_plural": "Tanzanian shillings"
    },
    {
        "symbol": "₴",
        "name": "Ukrainian Hryvnia",
        "symbol_native": "₴",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "UAH",
        "name_plural": "Ukrainian hryvnias"
    },
    {
        "symbol": "USh",
        "name": "Ugandan Shilling",
        "symbol_native": "USh",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "UGX",
        "name_plural": "Ugandan shillings"
    },
    {
        "symbol": "$U",
        "name": "Uruguayan Peso",
        "symbol_native": "$",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "UYU",
        "name_plural": "Uruguayan pesos"
    },
    {
        "symbol": "UZS",
        "name": "Uzbekistan Som",
        "symbol_native": "UZS",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "UZS",
        "name_plural": "Uzbekistan som"
    },
    {
        "symbol": "Bs.F.",
        "name": "Venezuelan Bolívar",
        "symbol_native": "Bs.F.",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "VEF",
        "name_plural": "Venezuelan bolívars"
    },
    {
        "symbol": "₫",
        "name": "Vietnamese Dong",
        "symbol_native": "₫",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "VND",
        "name_plural": "Vietnamese dong"
    },
    {
        "symbol": "FCFA",
        "name": "CFA Franc BEAC",
        "symbol_native": "FCFA",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "XAF",
        "name_plural": "CFA francs BEAC"
    },
    {
        "symbol": "CFA",
        "name": "CFA Franc BCEAO",
        "symbol_native": "CFA",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "XOF",
        "name_plural": "CFA francs BCEAO"
    },
    {
        "symbol": "YR",
        "name": "Yemeni Rial",
        "symbol_native": "ر.ي.‏",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "YER",
        "name_plural": "Yemeni rials"
    },
    {
        "symbol": "R",
        "name": "South African Rand",
        "symbol_native": "R",
        "decimal_digits": 2,
        "rounding": 0,
        "code": "ZAR",
        "name_plural": "South African rand"
    },
    {
        "symbol": "ZK",
        "name": "Zambian Kwacha",
        "symbol_native": "ZK",
        "decimal_digits": 0,
        "rounding": 0,
        "code": "ZMK",
        "name_plural": "Zambian kwachas"
    }
];
